### ISSUE TITLE
State of closed cover is not available

### ISSUE THREAD

**Issue by Lemocin** [SukramJ/hahomematic#125]
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.12.0

**Home Assistant version (if applicable):**
2021.12.7

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): piVCCU on oDroid C2
- OS (Original, RaspberryMatic, debmatic/...): CCU3
- Version: 3.61.7

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? idk, left it blank/0.0.0.0
Do you use username and password? Yes
Which interfaces do you use? HmIP, Bidcos-RF

**Describe the bug**
When i close a cover, it's state get's not available. The controls still work but the position slider disappears.

**To Reproduce**
1. Go to 'Settings - Devices - Hm local devices'
2. Click on 'any HmIP-BROLL Device, Steuerelemente'
3. Close cover

**Expected behavior**
State becomes closed and stays there,

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4162496/147964739-fb7194fd-4e5a-4269-b110-25d77c764fec.png)
![grafik](https://user-images.githubusercontent.com/4162496/147964716-6eced920-8c43-4231-8879-31ab3bc0337a.png)

**Comment by SukramJ** [comment]
Please add logs.

**Comment by Lemocin** [comment]
> Please add logs.

Where can i find them? HA doesn't show anything in the logs when closing/opening the cover.

**Comment by SukramJ** [comment]
I don't have a Broll, but i asked @itn3rd77, if he can reproduce this.

**Comment by itn3rd77** [comment]
I'll test and report back to you.

**Comment by itn3rd77** [comment]
Ok besides up and down working there is something strange as @Lemocin reported.

**I opened the cover an here is what it looks like:**

![grafik](https://user-images.githubusercontent.com/2655169/148018046-12c2b015-71c3-4e80-9590-17263ce90d82.png)

**The "Logbuch" message is wrong I opened the cover and it's reporting "Wurde geschlossen" ... mmmh**


**The status "Unbekannt" seems pretty new (maybe introduced in 0.12.0?). Didn't happen before:**

![grafik](https://user-images.githubusercontent.com/2655169/148018228-93697ded-2a5d-44f7-9460-095d8990f29a.png)

There are no errors in the logfile ...

**Comment by emufan** [comment]
Here was able to test similar behavior.

Nothing related in logs, but

1. I pressed close, I has been closed but then 
![image](https://user-images.githubusercontent.com/22775515/148027088-52436b76-de03-4068-999b-420f6c28da25.png)
and removed position slider
![image](https://user-images.githubusercontent.com/22775515/148027370-7243cf83-df9f-4c7d-aa50-84a7574a341f.png)
![image](https://user-images.githubusercontent.com/22775515/148027747-6dba7dde-6e47-489f-9746-a3e99845b6fa.png)
In Positions bwetween 0 and 100 it is with position attribute and with state.
Nothing in Log in the 

2. if completely **open** it is shown as **closed**
![image](https://user-images.githubusercontent.com/22775515/148027970-43cedd78-aa3c-4a22-a0f9-50565f7e7dc0.png)

**Comment by Lemocin** [comment]
Same for me, what surprised me though, is that in the current  shown closed (real opened) state, the open button is disabled and only the close and stop buttons are activated. This is the right behaviour besides the shown state. Also the position slider is still there. 

I also think this is pretty new. i looked in the logbook and the only not available before was at the 27.12.2021, but i think this was maybe a connection issue.

**Comment by SukramJ** [comment]
The slider disappears if you close the cover.
What happens if you open the cover?

**Comment by Lemocin** [comment]
> The slider disappears if you close the cover. What happens if you open the cover?

State shows closed, but only the stop and close button is active(the right behaviour, only shows wrong state).

**Comment by SukramJ** [comment]
Please open the cover. By CCU or by HA service. What happens?

**Comment by Lemocin** [comment]
Opened with HA:
![image](https://user-images.githubusercontent.com/4162496/148074880-5d6375bb-e1c9-481a-94c9-513168e973bb.png)
![image](https://user-images.githubusercontent.com/4162496/148074933-7b5caa69-524e-4d58-9f44-3d6e7d1f80eb.png)
Opened with CCU:
the same
![image](https://user-images.githubusercontent.com/4162496/148075188-fff6f2b3-047f-4a94-ba27-b36595db28a2.png)

Controls are working. Cover opens normally.

**Comment by SukramJ** [comment]
Please check latest version (0.13.0). I only found a minor issue, but i don't know if this is really related.

**Comment by Lemocin** [comment]
> Please check latest version (0.13.0). I only found a minor issue, but i don't know if this is really related.

I'm already on 0.13.0. The opened cover behaves still the same. Later i will check the closed state and report back.

**Comment by SukramJ** [comment]
btw  and not related to cover:
Do you read changelogs in hacs?
There is a small breaking change related to climate (Heating Groups).

**Comment by Lemocin** [comment]
> btw and not related to cover: Do you read changelogs in hacs? There is a small breaking change related to climate (Heating Groups).

Yes, before i update, i always read the changelog. The breaking change didn't affect me because i have the heating groups still disabled(and wasn't able to find out where to activate without recreating the integration)

**Comment by SukramJ** [comment]
This is a featue of the latest release. you now can reconfigure your setup.
Just click on "Konfigurieren".

**Comment by Lemocin** [comment]
Works like a charm - nice. But now i have every device two times(one with the old, dead entities like number.hmip_etrv_b1_id_active_profile, and one with the activated entities.) If i delete the dead entities, the device stays, but is empty. Any idea or is it better to just recreate the Integration?

![grafik](https://user-images.githubusercontent.com/4162496/148083471-6fb9a555-78e4-4090-89c7-cce42415c973.png)
![grafik](https://user-images.githubusercontent.com/4162496/148083516-53ed83af-757b-4bd0-a76f-23610c390e07.png)

**Comment by itn3rd77** [comment]
Hi,

tested on 0.13. For me everything seems OK except the Logbook messages.  Closed is reported as "wurde geöffnet" and Opend is reported as "wurde geschlossen"

![grafik](https://user-images.githubusercontent.com/2655169/148085554-ac43ac0f-1b4b-466b-a8b7-dd746bfdaec4.png)

**Comment by Lemocin** [comment]
> Closed is reported as "wurde geöffnet"

I can confirm this. The closed cover is now in the state "open"

**Comment by SukramJ** [comment]
@Lemocin just recreate the integration.

**Comment by emufan** [comment]
Tested in .13 in HA

Complete OPEN is shown as CLOSED with current_position: 100, slider shown, STATE is not active
Intermediate status is show as OPEN with e.g. current_position: 85, slider shown, STATE is active
Complete CLOSED is shown as OPEN with current_position: 0, slide now shown again and only the up arrow again,  STATE is active

Tested with steering-buttons in CCU: Every result the same.

Beside the closed <> open state, I like that closed or somehow closed is active. I did this with card_mod before.

**Comment by SukramJ** [comment]
Beside the inverted state your covers are now working?

**Comment by SukramJ** [comment]
I wonder if this state has ever been reported correct?

**Comment by emufan** [comment]
> Beside the inverted state your covers are now working?

Yes. afaik. See status above.

> I wonder if this state has ever been reported correct?

In this integration? Don't know. The old integration shows completely open as active. Partly open as active and closed as not active. Here personally I like it more if closed is active the as is situation in you integration. But I fear it is only because closed and open are currently set switched.

**Comment by Lemocin** [comment]
> Beside the inverted state your covers are now working?

Yes, they were always working. And the slider stays now. so everything is fine besides the inverted status



> I wonder if this state has ever been reported correct?

I have checked from 01.11.2021 to today and seems like it was always inverted. I just didn't noticed it, because the right buttons were always enabled and the level(slider) showed it correctly.

**Comment by Lemocin** [comment]
> @Lemocin just recreate the integration.

> This is a featue of the latest release. you now can reconfigure your setup.
> Just click on "Konfigurieren".


After doing anything of this, my sysvar entities have vanished. I have restarted HA and reloaded the integration multiple times. Did i do anything wrong or is this an issue? 
![grafik](https://user-images.githubusercontent.com/4162496/148099876-33e24205-7a75-4d41-ab12-fc31d7be583f.png)

**Comment by SukramJ** [comment]
Issue, but i already fixed it.

**Comment by Lemocin** [comment]
> Issue, but i already fixed it.

Nice, thank you. You're faster than lightning :D 

                    "enable_sensors_for_own_system_variables": true,
                    "enable_sensors_for_system_variables": true
I did add these entries in the core.config_entries meanwhile. That works too.

**Comment by SukramJ** [comment]
should be fixed with latest release

**Comment by Lemocin** [comment]
> should be fixed with latest release
Just Tested, seems to Work!

**Comment by chrste90** [comment]
Hi, for me it's still not working with a `HM-LC-Bl1PBU-FM`. Maybe there is a difference between HmIP and nonIP devices?

If it's closed: 
![Bildschirmfoto 2022-01-05 um 06 42 17](https://user-images.githubusercontent.com/6923277/148166485-f608ed61-b030-47c0-8971-77ad971d6d3b.png)

If it's not closed:
![Bildschirmfoto 2022-01-05 um 06 42 45](https://user-images.githubusercontent.com/6923277/148166536-3dcb7962-d007-4b6b-8373-35dfd168c51a.png)

In the log you can see that the closed state is not available and shown as "Nicht mehr verfügbar"

Is there anything i can provide to help find the root cause?

**Comment by itn3rd77** [comment]
Can confirm this (v0.13.1).
Seems I clicked two times a HmIP device yesterday for testing - sorry.

In the initial state it looked like @chrste90 wrote. Than I opened the cover. Which looks ok as I can't click open a second time.

![grafik](https://user-images.githubusercontent.com/2655169/148169100-bdec64bb-f3dd-429c-974d-576855b276f6.png)

But the status remains unknown:

![grafik](https://user-images.githubusercontent.com/2655169/148169237-9bd9efe3-75ba-486a-92d2-b47049beaf35.png)

**Comment by emufan** [comment]
> But the status remains unknown:

Are you sure? Can you show the status from develpment tools? As far as I can see, there is <> unknown pink bar on the right.

**Comment by itn3rd77** [comment]
Man thanks! You are right. Must have been blind this morning :-(

**Comment by SukramJ** [comment]
@chrste90 Please check latest release

**Comment by chrste90** [comment]
@SukramJ It's now working as expected, thanks for the quick fix.

But i have now a new slider for "Kippstellung":
![Bildschirmfoto 2022-01-05 um 10 54 43](https://user-images.githubusercontent.com/6923277/148197943-820abfaf-7c89-40f0-9ac3-ef198e224533.png)

Where does it come from? I don't think it's needed for this device.

**Comment by SukramJ** [comment]
Please open a new issue.

**Comment by emufan** [comment]
Tested for BROLL as well. Fine. open is open, intermediate open is open, closed is closed. Unfortunately and as expected, the active is now as in the old integration. open is active. Most probably derived directly from open. But this is only a personal favor to have it shown the other way round. I can stay with card_mod to "correct" it.

**Comment by chrste90** [comment]
@SukramJ 
I was just about to open a new issue when i saw your PR https://github.com/danielperna84/hahomematic/pull/137

This should remove the "Kippstellung" slider or am i wrong?

**Comment by SukramJ** [comment]
Yes.
